apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: mehnaaz/myapp:latest
          ports:
            - containerPort: 8081
          env:
            - name: SECRET_KEY
              value: "mehnaaz123"